version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/London
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: System.Net.Http
    versions:
    - "> 4.3.0, < 4.4"
