version: 1.2.{build}

environment:
  BrowserStack_UserName:
    secure: 1pPava/umi31t0fUJWpcaw==
  BrowserStack_AccessKey:
    secure: kTuv757nz0qovSIwBwGIIFeb2X3PXJuci0mJjGMJuIk=

assembly_info:
  patch: true
  file: AssemblyVersion.cs
  assembly_version: "1.2.0.0"
  assembly_file_version: "{version}.0"
  assembly_informational_version: "{version}.0"

build:
  project: src\MartinCostello.BrowserStack.Automate.msbuild
  verbosity: minimal

after_build:
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "src\BuildOutput\MartinCostello.BrowserStack.Automate_coverage.xml"

artifacts:
  - path: src\BuildOutput\*.nupkg

nuget:
  disable_publish_on_pr: true

skip_tags: false
test: off

deploy:

  - provider: NuGet
    api_key:
      secure: 7xiMOBgPvPg3LrtOPUFfhJJqcCU/fKHWG9WHVDgPnBI74dAd3lgeh1VxL7qjM5R0
    artifact: /.*\.nupkg/
    skip_symbols: false
    on:
      appveyor_repo_tag: true
