os: Visual Studio 2017
version: 3.0.0.{build}

environment:
  BrowserStack_UserName:
    secure: 1pPava/umi31t0fUJWpcaw==
  BrowserStack_AccessKey:
    secure: kTuv757nz0qovSIwBwGIIFeb2X3PXJuci0mJjGMJuIk=
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

branches:
  only:
    - master

build_script:
  - ps: .\Build.ps1

after_build:
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "artifacts\code-coverage.xml"

artifacts:
  - path: artifacts\*.nupkg

nuget:
  disable_publish_on_pr: true

skip_tags: false
test: off

deploy:

  - provider: NuGet
    api_key:
      secure: THNHTw3qtQXgSWiBS7JM5QNsO/59BuUUmej27zgoqLKVvZOdVf+0dfrho/jyBKmL
    artifact: /.*\.nupkg/
    skip_symbols: false
    on:
      appveyor_repo_tag: true
