os: Visual Studio 2015
version: 3.0.0.{build}

environment:
  BrowserStack_UserName:
    secure: 1pPava/umi31t0fUJWpcaw==
  BrowserStack_AccessKey:
    secure: kTuv757nz0qovSIwBwGIIFeb2X3PXJuci0mJjGMJuIk=
  CLI_VERSION: 1.0.0-preview2-003121
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

assembly_info:
  patch: true
  file: AssemblyVersion.cs
  assembly_version: "3.0.0.0"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

build_script:
  - ps: dotnet --info
  - ps: .\Build.ps1

artifacts:
  - path: artifacts\*.nupkg

nuget:
  disable_publish_on_pr: true

skip_tags: false
test: off

deploy:

  - provider: NuGet
    api_key:
      secure: 7xiMOBgPvPg3LrtOPUFfhJJqcCU/fKHWG9WHVDgPnBI74dAd3lgeh1VxL7qjM5R0
    artifact: /.*\.nupkg/
    skip_symbols: false
    on:
      appveyor_repo_tag: true
